import type { Collection, Paper } from "./types";

const min = 60_000;
const now = Date.now();

export const demoCollections: Collection[] = [
  { id: "c-diabetes", name: "Diabetes Research", description: "Metabolic therapies and outcomes", hue: 268 },
  { id: "c-cardio", name: "Cardiology", description: "Cardiovascular trials and meta-analyses", hue: 20 },
  { id: "c-onc", name: "Oncology", description: "Screening, detection and treatment", hue: 330 },
  { id: "c-ai", name: "AI in Healthcare", description: "Machine learning in clinical practice", hue: 195 },
];

export const demoPapers: Paper[] = [
  {
    id: "glp1-cvot",
    title: "Effects of GLP-1 Receptor Agonists on Cardiovascular Outcomes",
    authors: "Sample Author A., Sample Author B., et al.",
    journal: "Demo Journal of Cardiometabolic Medicine",
    published: "2024-03-12",
    doi: "10.0000/demo.glp1.2024",
    pmid: "DEMO-001",
    fileType: "pdf",
    fileName: "glp1_cardiovascular_meta.pdf",
    summarizedAt: now - 2 * min,
    favorite: true,
    saved: true,
    collectionIds: ["c-diabetes", "c-cardio"],
    tags: ["Meta-analysis", "Type 2 diabetes", "MACE"],
    sample: true,
    summary: {
      executive:
        "This meta-analysis of randomized cardiovascular outcome trials found that GLP-1 receptor agonists were associated with a reduction in major adverse cardiovascular events (MACE) in adults with type 2 diabetes, with consistent signals for cardiovascular death and stroke and a favorable safety profile.",
      objective:
        "To determine whether GLP-1 receptor agonists reduce major adverse cardiovascular events compared with placebo in adults with type 2 diabetes.",
      methodology: [
        { label: "Study design", value: "Systematic review and meta-analysis of RCTs" },
        { label: "Population", value: "Adults with type 2 diabetes at elevated CV risk" },
        { label: "Sample size", value: "8 trials · ~60,000 participants" },
        { label: "Intervention", value: "GLP-1 receptor agonist vs placebo" },
        { label: "Analysis", value: "Random-effects model, hazard ratios with 95% CI" },
      ],
      findings: [
        "MACE reduced by ~14% (HR 0.86, 95% CI 0.80–0.93).",
        "Cardiovascular death reduced by ~13% (HR 0.87).",
        "Fatal or non-fatal stroke reduced by ~17% (HR 0.83).",
        "Hospitalization for heart failure reduced by ~11%.",
        "No significant increase in severe hypoglycemia or pancreatitis.",
      ],
      conclusion:
        "GLP-1 receptor agonists provide cardiovascular benefit in type 2 diabetes, supporting their use in patients with established or high-risk cardiovascular disease.",
      clinical:
        "The findings support considering cardiovascular risk alongside glycemic control when selecting glucose-lowering therapy. Applicability to individual patients should be assessed against current guidelines.",
      limitations: [
        "Heterogeneity in agents, dosing and trial duration.",
        "Trials were industry-funded.",
        "Limited representation of low-risk populations.",
      ],
      takeaways: [
        "~14% relative reduction in MACE",
        "Benefit consistent across CV death and stroke",
        "Safety profile broadly favorable",
        "Evidence strongest in high-risk patients",
      ],
    },
    compare: {
      design: "Meta-analysis of RCTs",
      population: "Adults with T2D, high CV risk",
      sampleSize: "~60,000",
      intervention: "GLP-1 RA vs placebo",
      outcome: "3-point MACE",
    },
  },
  {
    id: "ai-cancer",
    title: "Artificial Intelligence in Early Cancer Detection",
    authors: "Sample Author C., Sample Author D.",
    journal: "Demo Reviews in Digital Oncology",
    published: "2024-01-28",
    doi: "10.0000/demo.aionc.2024",
    fileType: "pdf",
    fileName: "ai_early_cancer_detection.pdf",
    summarizedAt: now - 3 * 60 * min,
    favorite: false,
    saved: true,
    collectionIds: ["c-onc", "c-ai"],
    tags: ["Deep learning", "Screening", "Imaging"],
    sample: true,
    summary: {
      executive:
        "This review evaluates deep-learning systems for early cancer detection across mammography, low-dose CT and dermatology imaging, reporting diagnostic performance comparable to specialists in retrospective settings, with limited prospective validation.",
      objective: "To assess the diagnostic accuracy and readiness of AI models for early detection of common cancers.",
      methodology: [
        { label: "Study design", value: "Narrative and quantitative review" },
        { label: "Population", value: "Screening and diagnostic imaging cohorts" },
        { label: "Sample size", value: "42 studies" },
        { label: "Intervention", value: "Deep-learning image classification" },
        { label: "Analysis", value: "Pooled sensitivity, specificity, AUC" },
      ],
      findings: [
        "Pooled AUC of 0.91 across included imaging tasks.",
        "AI-assisted reading reduced false negatives in mammography by ~9%.",
        "Only 6 of 42 studies were prospective.",
        "Performance dropped on external validation datasets.",
      ],
      conclusion: "AI shows promise as a second reader, but prospective, multi-site trials are needed before routine adoption.",
      clinical: "AI may support radiologists in high-volume screening; integration should be accompanied by monitoring for bias and performance drift.",
      limitations: ["Predominantly retrospective data.", "Dataset shift between institutions.", "Inconsistent reporting standards."],
      takeaways: ["Specialist-level accuracy in retrospective studies", "Best used as a second reader", "Prospective evidence is scarce"],
    },
    compare: {
      design: "Systematic review",
      population: "Imaging screening cohorts",
      sampleSize: "42 studies",
      intervention: "Deep-learning models",
      outcome: "Diagnostic accuracy (AUC)",
    },
  },
  {
    id: "sglt2-long",
    title: "Long-term Outcomes of SGLT2 Inhibitors",
    authors: "Sample Author E., Sample Author F., et al.",
    journal: "Demo Journal of Renal & Metabolic Research",
    published: "2023-11-04",
    pmid: "DEMO-003",
    fileType: "text",
    summarizedAt: now - 26 * 60 * min,
    favorite: true,
    saved: false,
    collectionIds: ["c-diabetes"],
    tags: ["Cohort", "Kidney outcomes", "Heart failure"],
    sample: true,
    summary: {
      executive:
        "In a long-term observational cohort, SGLT2 inhibitor use was associated with slower decline in kidney function and fewer heart-failure hospitalizations compared with other second-line glucose-lowering agents over a median of 5 years.",
      objective: "To evaluate the durability of renal and cardiovascular benefits of SGLT2 inhibitors beyond trial follow-up periods.",
      methodology: [
        { label: "Study design", value: "Retrospective cohort study" },
        { label: "Population", value: "Adults with T2D starting second-line therapy" },
        { label: "Sample size", value: "48,210 patients" },
        { label: "Intervention", value: "SGLT2 inhibitor vs DPP-4 inhibitor" },
        { label: "Analysis", value: "Propensity-score matched Cox models" },
      ],
      findings: [
        "eGFR decline slowed by 1.1 mL/min/1.73m² per year.",
        "Heart-failure hospitalization reduced by ~30% (HR 0.70).",
        "Benefits sustained over median 5.2-year follow-up.",
        "Genital mycotic infections more frequent.",
      ],
      conclusion: "Renal and heart-failure benefits of SGLT2 inhibitors appear durable in routine practice.",
      clinical: "Supports long-term continuation where indicated; observational design means causal inference is limited.",
      limitations: ["Residual confounding possible.", "Data from a single health system.", "Adherence not directly measured."],
      takeaways: ["Durable kidney protection", "~30% fewer HF hospitalizations", "Observational — confirm with RCT data"],
    },
    compare: {
      design: "Retrospective cohort",
      population: "Adults with T2D, second-line therapy",
      sampleSize: "48,210",
      intervention: "SGLT2i vs DPP-4i",
      outcome: "eGFR decline, HF hospitalization",
    },
  },
  {
    id: "ml-sepsis",
    title: "Machine Learning for Early Detection of Sepsis",
    authors: "Sample Author G., Sample Author H.",
    journal: "Demo Critical Care Informatics",
    published: "2024-05-19",
    doi: "10.0000/demo.sepsis.2024",
    fileType: "image",
    fileName: "sepsis_abstract_scan.png",
    summarizedAt: now - 3 * 24 * 60 * min,
    favorite: false,
    saved: true,
    collectionIds: ["c-ai"],
    tags: ["ICU", "Prediction model", "EHR"],
    sample: true,
    summary: {
      executive:
        "A gradient-boosted model using routine EHR vitals and labs predicted sepsis onset a median of 4 hours before clinical recognition in ICU patients, with external validation showing moderate performance loss.",
      objective: "To develop and validate a machine-learning model for early prediction of sepsis in hospitalized patients.",
      methodology: [
        { label: "Study design", value: "Model development + external validation" },
        { label: "Population", value: "Adult ICU admissions" },
        { label: "Sample size", value: "31,500 admissions" },
        { label: "Intervention", value: "Gradient-boosted prediction model" },
        { label: "Analysis", value: "AUROC, lead time, calibration" },
      ],
      findings: [
        "AUROC 0.87 internally; 0.81 on external validation.",
        "Median lead time of 4 hours before clinical diagnosis.",
        "Alert burden of ~1.2 alerts per patient-day.",
      ],
      conclusion: "ML-based early warning can identify sepsis earlier, but alert fatigue and generalizability need addressing.",
      clinical: "Could support earlier evaluation and treatment workflows; deployment requires local validation.",
      limitations: ["Retrospective labels of sepsis onset.", "Performance drop across sites.", "No outcome impact trial."],
      takeaways: ["~4h earlier detection", "Moderate external performance", "Needs prospective impact studies"],
    },
    compare: {
      design: "Prognostic model study",
      population: "Adult ICU admissions",
      sampleSize: "31,500",
      intervention: "ML early-warning model",
      outcome: "Sepsis onset prediction",
    },
  },
];
